# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
swap_factors <- function(ids_to_swap, munged_col, first_nns, var_param) {
    .Call(`_distillery_swap_factors`, ids_to_swap, munged_col, first_nns, var_param)
}

#' @export
swap_numerics <- function(ids_to_swap, munged_col, first_nns, var_param) {
    .Call(`_distillery_swap_numerics`, ids_to_swap, munged_col, first_nns, var_param)
}

